### ISSUE TITLE
Conflicts with puppet-lint 2

### ISSUE THREAD

**Issue by amosshapira** [camptocamp/puppet-ghostbuster#61]
When I tried to run it with puppet-lint 2.0.2 installed on my system I got:

```
$ find -type f -exec puppet-lint --only-checks ghostbuster_classes,ghostbuster_defines,ghostbuster_facts,ghostbuster_files,ghostbuster_functions,ghostbuster_hiera_files,ghostbuster_templates,ghostbuster_types {} \+
/Users/amos.shapira/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate puppet-ghostbuster-0.7.3, because puppet-lint-2.0.2 conflicts with puppet-lint (~> 1.0) (Gem::ConflictError)
    from /Users/amos.shapira/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1280:in `activate'
    from /Users/amos.shapira/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
    from /Users/amos.shapira/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
    from /Users/amos.shapira/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
    from /Users/amos.shapira/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
    from /Users/amos.shapira/.rvm/gems/ruby-2.1.3/gems/puppet-ghostbuster-0.7.3/lib/puppet-lint/plugins/check_ghostbuster_classes.rb:1:in `<top (required)>'
    from /Users/amos.shapira/.rvm/gems/ruby-2.1.3/gems/puppet-lint-2.0.2/lib/puppet-lint/plugins.rb:18:in `load'
    from /Users/amos.shapira/.rvm/gems/ruby-2.1.3/gems/puppet-lint-2.0.2/lib/puppet-lint/plugins.rb:18:in `block (2 levels) in load_from_gems'
    from /Users/amos.shapira/.rvm/gems/ruby-2.1.3/gems/puppet-lint-2.0.2/lib/puppet-lint/plugins.rb:17:in `each'
    from /Users/amos.shapira/.rvm/gems/ruby-2.1.3/gems/puppet-lint-2.0.2/lib/puppet-lint/plugins.rb:17:in `block in load_from_gems'
    from /Users/amos.shapira/.rvm/gems/ruby-2.1.3/gems/puppet-lint-2.0.2/lib/puppet-lint/plugins.rb:16:in `each'
    from /Users/amos.shapira/.rvm/gems/ruby-2.1.3/gems/puppet-lint-2.0.2/lib/puppet-lint/plugins.rb:16:in `load_from_gems'
    from /Users/amos.shapira/.rvm/gems/ruby-2.1.3/gems/puppet-lint-2.0.2/lib/puppet-lint/plugins.rb:74:in `<top (required)>'
    from /Users/amos.shapira/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/amos.shapira/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/amos.shapira/.rvm/gems/ruby-2.1.3/gems/puppet-lint-2.0.2/lib/puppet-lint.rb:214:in `<top (required)>'
    from /Users/amos.shapira/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/amos.shapira/.rvm/rubies/ruby-2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/amos.shapira/.rvm/gems/ruby-2.1.3/gems/puppet-lint-2.0.2/bin/puppet-lint:5:in `<top (required)>'
    from /Users/amos.shapira/.rvm/gems/ruby-2.1.3/bin/puppet-lint:23:in `load'
    from /Users/amos.shapira/.rvm/gems/ruby-2.1.3/bin/puppet-lint:23:in `<main>'
    from /Users/amos.shapira/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
    from /Users/amos.shapira/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

any chance of making it work with puppet-lint 2?

**Comment by amosshapira** [comment]
Thanks!
